alter table public.tournaments
  add column if not exists start_at timestamptz,
  add column if not exists end_at timestamptz,
  add column if not exists location text,
  add column if not exists address text,
  add column if not exists yandex_maps_url text,
  add column if not exists poster_url text,
  add column if not exists description text,
  add column if not exists event_url text,
  add column if not exists source text not null default 'manual',
  add column if not exists google_event_id text,
  add column if not exists registration_chat_id text;

create unique index if not exists tournaments_google_event_id_key
  on public.tournaments (google_event_id)
  where google_event_id is not null;

create table if not exists public.tournament_registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  user_telegram_id bigint not null,
  user_name text not null,
  venue_title text not null,
  created_at timestamptz not null default now(),
  unique (tournament_id, user_telegram_id)
);

create index if not exists tournament_registrations_tournament_id_idx
  on public.tournament_registrations (tournament_id);

alter table public.tournament_registrations enable row level security;

revoke all on table public.tournament_registrations from anon, authenticated;
revoke all on sequence public.tournament_registrations_id_seq from anon, authenticated;
grant all on table public.tournament_registrations to service_role;
grant all on sequence public.tournament_registrations_id_seq to service_role;

do $$
begin
  create policy "Tournament registrations are server-managed"
    on public.tournament_registrations
    for all
    using (false)
    with check (false);
exception
  when duplicate_object then null;
end $$;
